variables:
  STORE_DIR: "${CI_PROJECT_DIR}/.cabal-store"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - .cabal-store
    - dist-newstyle/cache

before_script:
  - apt -qq update
  - cabal update

test:8.4:
  image: haskell:8.4
  script:
    - cabal --store-dir=$STORE_DIR new-test

test:8.2:
  image: haskell:8.2
  script:
    - cabal --store-dir=$STORE_DIR new-test

